#!/usr/bin/env ruby
require 'yaml'
$config=YAML.load_file("/stegodb/config.yml")
require 'optparse'
require '/stegodb/downstream/stegoFeed'
$logger=Logger.new(STDOUT)

# downstream: digestion of data
outpath=nil
OptionParser.new do |opts|
  opts.on("-o", "--out=value", String) { |value| outpath = value }
end.parse!
raise 'usage: pipeline.rb -o <output path>' if outpath.nil? 

stegofeed=Feeder.new
stegofeed.impactFTP(outpath=outpath)
